name: Build Docker Image and Trivy Scan

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: |
        docker build -t react:latest .

    - name: Set up Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'react:latest'
        format: 'table'
        output: 'vun.txt'  # Save Trivy scan results to vun.txt

    - name: Save Trivy Scan Results
      run: mv vun.txt $GITHUB_WORKSPACE/vun.txt

    - name: Run Trivy Scan on Docker Image
      run: trivy image --exit-code 1 react:latest

    - name: Push Docker Image to Docker Hub
      if: success()
      run: docker push react:latest
