name: Destroy AWS Resources

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day
  workflow_dispatch:    # Allows manual triggering

jobs:
  destroy-resources:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Cloud Nuke
        run: |
          curl -LO https://github.com/gruntwork-io/cloud-nuke/releases/download/v0.37.1/cloud-nuke_linux_amd64
          chmod +x cloud-nuke_linux_amd64
          sudo mv cloud-nuke_linux_amd64 /usr/local/bin/cloud-nuke

      - name: Verify Cloud Nuke Installation
        run: |
          /usr/local/bin/cloud-nuke --version

      - name: List Supported Resource Types
        run: |
          /usr/local/bin/cloud-nuke aws --list-resource-types

      - name: Prepare Exclusions for Cloud Nuke
        env:
          DISABLE_TELEMETRY: true
        run: |
          # Loop through each excluded resource name file and construct exclusion flags
          exclude_args=""
          for file in excluded_instances.txt excluded_buckets.txt excluded_roles.txt excluded_users.txt; do
            if [ -f "$file" ]; then
              exclude_args+=" --exclude-resource-name $(cat $file)"
            fi
          done

          # Run Cloud Nuke with exclusion flags and other parameters
          /usr/local/bin/cloud-nuke aws --region us-east-1 --region us-east-2 --force --older-than 24h $exclude_args
