name: Destroy AWS Resources

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day
  workflow_dispatch:    # Allows manual triggering

jobs:
  destroy-resources:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Cloud Nuke
        run: |
          wget https://github.com/gruntwork-io/cloud-nuke/releases/download/v0.10.1/cloud-nuke_linux_amd64 -O cloud-nuke
          chmod +x cloud-nuke
          sudo mv cloud-nuke /usr/local/bin/cloud-nuke

      - name: Verify Cloud Nuke Installation
        run: |
          /usr/local/bin/cloud-nuke --version

      - name: Run Cloud Nuke
        run: |
          /usr/local/bin/cloud-nuke aws --region us-east-1 --region us-east-2 --force

  re-run:
    needs: [destroy-resources]
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Trigger manual re-run
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }}
