name: Build Docker Image, Trivy Scan, and Renovate

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0/15 * * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.7
        with:
          renovate-version: full
          token: ${{ secrets.RENOVATE_TOKEN }}
