name: Renovate

on:
  push:
  workflow_dispatch:

jobs:
  renovate:
    uses: amanverma678/shared-workflows/.github/workflows/renovate.yml@main
    with:
      renovate_config: ".github/workflows/example/renovate-config.json"
      renovate_token: ${{ secrets.RENOVATE_TOKEN }}


